// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DiaBLE Playground",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "DiaBLE Playground",
            targets: ["AppModule"],
            bundleIdentifier: "name.soranzio.guido.diable.DiaBLE-Playground",
            teamIdentifier: "Z25SC9UDC8",
            displayVersion: "0.0.1",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .bluetoothAlways(purposeString: "DiaBLE uses Bluetooth to receive glucose data and alarms from several transmitters and Libre sensors"),
                .calendars(purposeString: "DiaBLE creates events to be displayed in Apple Watch complications")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
